name: learn-github-actions
run-name: ${{ github.actor }} is deploying an update
on: [push]
jobs:
  configure-update:
    runs-on: self-hosted
    steps:
      - name: reinstall dependencies
        run: |
          cd /var/www/html/track-keeper/front 
          npm i
          npm audit fix
          cd /var/www/html/track-keeper/api
          npm i
          npm audit fix
      - name: transpile web
        run: |
          cd /var/www/html/track-keeper/front
          npm run build
      
      - name: restart api service
        run: |
          systemctl restart track-keeper.service
          systemctl status track-keeper.service