name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: self-hosted
    steps:
      - name: pull from repo  
        run: |
          cd /var/www/html/track-keeper
          ls -l 
          git stashgit pull -q --force;
          if [! -d "/var/www/html/track-keeper/api/storage" ]; then
            cd /var/www/html/track-keeper/api
            mkdir storage
            cd storage
            mkdir covers
            mkdir profile
          fi